spring.application.name=rosca-system

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/rosca_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

jwt.secret=${jwt_secret:defaultSecretKeyThatIsAtLeast32BytesLongForHS256Algorithm123}
jwt.expiration=${jwt_expiration:86400000}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mock OAuth2 properties so the app can start
spring.security.oauth2.client.registration.google.client-id=mock-client-id
spring.security.oauth2.client.registration.google.client-secret=mock-client-secret
spring.security.oauth2.client.registration.google.scope=profile,email

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
