/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as Oauth2RedirectRouteImport } from './routes/oauth2.redirect'
import { Route as AppGroupsIndexRouteImport } from './routes/_app.groups.index'
import { Route as AppGroupsIdRouteImport } from './routes/_app.groups.$id'
import { Route as AppGroupsCreateRouteImport } from './routes/_app.groups.create'
import { Route as AppGroupsIdAuctionRouteImport } from './routes/_app.groups_.$id.auction'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const Oauth2RedirectRoute = Oauth2RedirectRouteImport.update({
  id: '/oauth2/redirect',
  path: '/oauth2/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIdRoute = AppGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsCreateRoute = AppGroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIdAuctionRoute = AppGroupsIdAuctionRouteImport.update({
  id: '/groups_/$id/auction',
  path: '/groups/$id/auction',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/oauth2/redirect': typeof Oauth2RedirectRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/groups/create': typeof AppGroupsCreateRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/groups/$id/auction': typeof AppGroupsIdAuctionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/wallet': typeof AppWalletRoute
  '/oauth2/redirect': typeof Oauth2RedirectRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/groups/create': typeof AppGroupsCreateRoute
  '/groups': typeof AppGroupsIndexRoute
  '/groups/$id/auction': typeof AppGroupsIdAuctionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/wallet': typeof AppWalletRoute
  '/oauth2/redirect': typeof Oauth2RedirectRoute
  '/_app/groups/$id': typeof AppGroupsIdRoute
  '/_app/groups/create': typeof AppGroupsCreateRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/groups_/$id/auction': typeof AppGroupsIdAuctionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/wallet'
    | '/oauth2/redirect'
    | '/groups/$id'
    | '/groups/create'
    | '/groups/'
    | '/groups/$id/auction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/wallet'
    | '/oauth2/redirect'
    | '/groups/$id'
    | '/groups/create'
    | '/groups'
    | '/groups/$id/auction'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/wallet'
    | '/oauth2/redirect'
    | '/_app/groups/$id'
    | '/_app/groups/create'
    | '/_app/groups/'
    | '/_app/groups_/$id/auction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  Oauth2RedirectRoute: typeof Oauth2RedirectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth2/redirect': {
      id: '/oauth2/redirect'
      path: '/oauth2/redirect'
      fullPath: '/oauth2/redirect'
      preLoaderRoute: typeof Oauth2RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$id': {
      id: '/_app/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AppGroupsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/create': {
      id: '/_app/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AppGroupsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups_/$id/auction': {
      id: '/_app/groups_/$id/auction'
      path: '/groups/$id/auction'
      fullPath: '/groups/$id/auction'
      preLoaderRoute: typeof AppGroupsIdAuctionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWalletRoute: typeof AppWalletRoute
  AppGroupsIdRoute: typeof AppGroupsIdRoute
  AppGroupsCreateRoute: typeof AppGroupsCreateRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppGroupsIdAuctionRoute: typeof AppGroupsIdAuctionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppWalletRoute: AppWalletRoute,
  AppGroupsIdRoute: AppGroupsIdRoute,
  AppGroupsCreateRoute: AppGroupsCreateRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppGroupsIdAuctionRoute: AppGroupsIdAuctionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  Oauth2RedirectRoute: Oauth2RedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
